// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ugdolxrjjnsiqiwxjsso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZG9seHJqam5zaXFpd3hqc3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MzIyMzYsImV4cCI6MjA3NjMwODIzNn0.POkCfrdx_W_imwu86vweymPNtmaZkzxgX81w2gSL-vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);